package ee.pw.edu.pl.domain.usecase.test

enum class TestAnswer {
    NO,
    YES,

    EYES_BROWN, EYES_GREEN, EYES_GRAY, EYES_HAZEL, EYES_HONEY, EYES_LIGHT_BLUE, EYES_DARK_BLUE, EYES_AMETHYST,

    HAIR_BLONDE, HAIR_BROWN, HAIR_BLACK, HAIR_RED,

    RECREATION_HOME, RECREATION_OUTSIDE,

    PEOPLE_SMALLER, PEOPLE_BIGGER,

    BELIEF_RIGHT, BELIEF_LIBERAL, BELIEF_LEFT,

    MONEY_HIGH, MONEY_MEDIUM, MONEY_LOW,

    MIND_LOGICAL, MIND_INTERPERSONAL, MIND_VISUAL, MIND_MUSICAL, MIND_LINGUISTIC, MIND_KINESTHETIC, MIND_INTRAPERSONAL, MIND_NATURAL,
}
