package ee.pw.edu.pl.domain.usecase.account

enum class TestAnswer {
    NO,
    YES,

    EYES_BROWN, EYES_GREEN, EYES_BLUE,

    HAIR_BLONDE, HAIR_BROWN, HAIR_RED,

    RECREATION_HOME, RECREATION_OUTSIDE,

    PEOPLE_SMALLER, PEOPLE_BIGGER,

    BELIEF_RIGHT, BELIEF_LIBERAL, BELIEF_LEFT,

    MONEY_HIGH, MONEY_MEDIUM, MONEY_LOW,

    MIND_SCIENTIFIC, MIND_HUMANISTIC, MIND_ARTISTIC,
}
